#!/usr/bin/python
# script to take the tokenized output of a LightSpeed Pascal (LSP) file,
# typically as generated by lspTokenizer.py, and, based on a Pascal grammar,
# emit a parse tree, in JSON format.

